#define NUM_LEVELS 21
extern int level_change_timer;
extern int level_end_timer;

void level_up (void);
void level_change_pause (void);
void level_end (void);

void level_one (void);
void level_two (void);
void level_three (void);
void level_four (void);
void level_five (void);
void level_six (void);
void level_seven (void);
void level_eight (void);
void level_nine (void);
void level_ten (void);
void level_eleven (void);
void level_twelve (void);
void level_thirteen (void);
void level_fourteen (void);
void level_fiveteen (void);
void level_sixteen (void);
void level_seventeen (void);
void level_eighteen (void);
void level_nineteen (void);
void level_twenty (void);
void level_twentyone (void);
